fix toolbar test
gemini-testing/hermione-safari-commands pull request #19
Opened 2021-11-12 13:05 UTC by rostik404

2021-11-18 22:15 UTC, OldSkyTree commented on lib/utils.js
> +exports.isNewSafari = (browser) => Boolean(parseInt(browser.capabilities.version) >= NEW_SAFARI_VERSION);
кажется, что более универсальной была бы функция `isSafaryVersion`, в которую бы передавать конкретную версию. Тогда бы мы не завязывались на то, что этот сафари новый, что через какое-то время будет не так, а сразу будет видно, что это связанно с какими-то изменениями в конкретной версии. Также это поможет при внесении изменений для следующих версий

2021-11-18 22:15 UTC, OldSkyTree commented on lib/utils.js
> +exports.isNewSafari = (browser) => Boolean(parseInt(browser.capabilities.version) >= NEW_SAFARI_VERSION);
это было бы применимо и для wdio, но оно уже написано как есть

2021-11-19 10:10 UTC, DudaGod requested changes
Кажется, что можно сильно упростить код и уменьшить связанность если определять локаторы и хелперы в основном файле плагина. А затем их прокидывать во все команды. За счет этого команды ничего не будут знать о том, что существует какая-то другая версия safari и будут просто юзать локаторы и хелперы, которые ей передали. Так же за счет этого упростится поддержка в будущем.

2021-11-19 10:10 UTC, DudaGod commented on lib/command-helpers/element-utils/index.js
> +        return require('./common')(require('./new-safari'));
не очень удобная запись. Я бы в константу заносил.
Ну и подобным реквайром по условию вряд ли в данном случае что-то оптимизирует, т.е. можно было бы не парится и прям сверху все необходимые модули реквайрить.

У нас же бандл тут никакой не собирается, который должен включать только необходимую логику и весить как можно меньше.

2021-11-19 10:10 UTC, DudaGod commented on lib/native-locators.js
> +    VIEW_PORT: '//XCUIElementTypeWebView[@name="WebView"]/XCUIElementTypeWebView/XCUIElementTypeWebView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther'
Топовые локаторы получились )

2021-11-19 10:10 UTC, DudaGod commented on lib/native-locators.js
> +    return Object.assign(commonLocators, oldSafariLocators);
Уже ведь можно юзать записи вида - `{...commonLocators, ... safariNewLocators}`.

2021-11-19 11:44 UTC, rostik404 commented on lib/utils.js
> +exports.isNewSafari = (browser) => Boolean(parseInt(browser.capabilities.version) >= NEW_SAFARI_VERSION);
>  Т.е. логика по проверки версии растекается в кучу мест. Почему бы не определять это в одном месте с помощью фабрики? Например, как делал Саня тут - https://nda.ya.ru/t/Wazw3CL14W6nv8.

Так у меня по сути тоже самое - есть фабрика локаторов и фабрика utils-ов (да, они явно не называются фабрикой, могу переименовать модули 🙂), которые в зависимости от переданной версии браузера возвращают тебе нужный набор модулей с одинаковым интерфейсом. И в примере, который ты скинул, эта логика тоже "растекается в кучу мест" ([вот](https://nda.ya.ru/t/S54enX-E4W8SuM) и [вот](https://nda.ya.ru/t/w0nVsM4I4W8URh)), только я кусок логики вынес в хелпер.

По поводу того, чтобы эти фабрики инициализировать выше и прокидывать в каждую команду - вроде хорошая идея, попробую так и сделать

2021-11-19 12:00 UTC, rostik404 commented on lib/command-helpers/element-utils/common.js
> +        const {BOTTOM_TOOLBAR} = getNativeLocators(browser);
> И каждая команда знает, что есть различные версии локаторов и хелперов. Хотя ей про это знать вообще не нужно.

Ну вообще то не знает. У команд есть единая точка входа `getNativeLocators`, которая возвращает локаторы и такая же есть для хелперов (функция, которую экспортирует `element-utils/index.js`).

Прокинуть хелперы сверху - вроде норм, хотя если так подумать, для команд запись не сильно поменяется

Было:
```
module.exports = (browser) => {
    const {getElemCenterLocation} = require('../command-helpers/element-utils')(browser);
    ...
```
Станет:
```
module.exports = (browser, utils) => {
    const {getElemCenterLocation} = utils;
```

2021-11-30 18:31 UTC, rostik404 commented on lib/command-helpers/element-utils/<v15.0/index.js
> +'use strict';
Если придумаете, как лучше назвать файл с логикой для всех сафари, которые ниже 15-го, я буду только рад :)

2021-11-30 18:33 UTC, rostik404 commented on lib/index.js
> +            browserCommands[commandName](browser, {config: broConfig, locators, elementUtils});
Теперь локаторы и elementUtils пробрасываю в команды из корневой точки плагина

2021-12-02 08:54 UTC, DudaGod approved these changes
/ok

2021-12-02 08:54 UTC, DudaGod commented on .eslintrc.js
> +    parserOptions: {ecmaVersion: 2018},
а что ты юзаешь из ecma2018 ?

2021-12-02 08:54 UTC, DudaGod commented on lib/command-helpers/element-utils/<v15.0/index.js
> +'use strict';
А точно нужно эту информацию отражать в названии папки? При этом старый код работал только с 11, 12 и 13 версией. А с 14 мы вроде бы его не проверяли. Ну и так же вряд ли он работает с 1-10 версиями. В итоге если все это учесть, то название совсем странное получается )

2021-12-02 09:11 UTC, rostik404 commented on .eslintrc.js
> +    parserOptions: {ecmaVersion: 2018},
Это чтобы spread работал `{...{foo: 1}, ...{bar: 2}}`

2021-12-02 09:44 UTC, rostik404 commented on lib/command-helpers/element-utils/<v15.0/index.js
> +'use strict';
> А точно нужно эту информацию отражать в названии папки?
Ну как-то разделить то все равно нужно новую реализацию от старой. Причем сделать это так, чтобы можно было написать еще одну\несколько реализаций (это я к тому, что old-safari/new-safari как в первой моей реализации - было так себе решение)

> А с 14 мы вроде бы его не проверяли
Ну мы не проверяли, но теоретически, кто-то мог на это завязаться и если сейчас сделать по другому, то кому-то можем сломать гермиону.

2021-12-03 14:31 UTC, merged