Hermione 452 switch from pngjs to sharp
gemini-testing/hermione-safari-commands pull request #24
Opened 2023-03-02 16:07 UTC by c1825846

2023-03-02 16:10 UTC, c1825846 commented
Тесты и обработку ошибок допишу

2023-03-03 08:11 UTC, KuznetsovRoman commented on lib/commands/screenshot.js
> -const streamifier = require('streamifier');
Вот эти вот два пакета где-то еще в этом репозитории использовались? Вроде нет. Почему бы тогда их тоже не выпилить?

2023-03-03 08:12 UTC, KuznetsovRoman commented on package.json
> +    "sharp": "^0.31.3",
Нельзя ставить "^" на sharp, он особенный. Ему только "~", а какую именно минорную версию - нужно подумать

2023-03-03 08:30 UTC, KuznetsovRoman commented on package.json
> +    "sharp": "^0.31.3",
UPD: минор оставляем тот же, тогда "^" замени на "~", и явно уточни в package.json минимальную версию ноды с которой работает эта версия sharp

2023-03-03 10:29 UTC, c1825846 commented on package.json
> +    "sharp": "^0.31.3",
Ради общего развития, чем шарп особенный? Можешь рассказать или ссылкой кинуть, где почитать?

2023-03-03 10:37 UTC, KuznetsovRoman commented on package.json
> +    "sharp": "^0.31.3",
Обычно пакеты придерживаются (или, по крайней мере, стараются) семантического версионирования, и крышечка перед версией подразумевает, что пользователь однажды с гермионой не установит пакет, который будет несовместим с его текущей конфигурацией, которая была раньше. Но для шарпа это не так, потому что у него breaking changes не на мажорных релизах, а на минорных: так вот 0.31 перестал поддерживать 12 ноду (https://sharp.pixelplumbing.com/changelog#v0310---5th-september-2022).

2023-03-07 06:29 UTC, xrsd commented on test/lib/commands/screenshot.js
> +    it('should take into a count pixelRatio', async () => {
should [take into account](https://translate.yandex.ru/?source_lang=en&target_lang=ru&text=take%20into%20account) pixel ratio

и еще добавить тест на то, что `body.width` используется

2023-03-13 14:03 UTC, DudaGod requested changes
Есть вопросы к тестам

2023-03-13 14:03 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +            'sharp': mockedSharp
Так тоже делать не нужно. Достаточно сделать `mockedSharp` глобальным.

2023-03-13 14:03 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +        await assert.isRejected(browser.takeScreenshot(), 'o.O');
Не очень понятно, что ты тут тестируешь. Ты же никакие `try catch` не навешиваешь. Соответственно любой exception полетит наружу.

2023-03-14 08:32 UTC, c1825846 commented on lib/commands/screenshot.js
> +            .extract({left: cropCoords.left, top: cropCoords.top, width: cropCoords.width, height: cropCoords.height})
имеешь ввиду добавить .catch и выкинуть в нём свою ошибку?

2023-03-14 11:49 UTC, KuznetsovRoman commented on test/lib/commands/screenshot.js
> +        toBuffer = sinon.stub().named('extract').resolves(buf);
Почему `toBuffer`, но `named('extract')`?

2023-03-16 09:21 UTC, DudaGod requested changes
Еще остались вопросы

2023-03-16 09:21 UTC, DudaGod commented on lib/commands/screenshot.js
> +            };
А зачем так ошибку бросать то? Почему просто не написать `throw new Error('Failed to take screenshot:', e)`?

2023-03-16 09:21 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +        stub.toBuffer = sinon.stub().resolves({data: 'buffer', info: {channels: 3, width: 100500, height: 500100}});
У тебя `toBuffer` должен тут возвращать какой-то дефолтный буфер. Например `Buffer.from('default-data')`

2023-03-16 09:21 UTC, DudaGod commented on test/lib/commands/screenshot.js
> -    it('should capture the whole page using base "takeScreenshot" command before starting to handle it', async () => {
Тут тот же самый вопрос остался.

2023-03-16 09:21 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +            height: 2
А чего ты эти координаты просто не сохранить в объект? Типа - `const coords = {left: 0, top: 0, width: 2, height: 2}`. И потом его везде юзать можно и дублировать.

2023-03-16 09:21 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +            pixelRatio: 1
`pixelRatio` и `width` тоже можно из переменных тут юзать.

2023-03-16 09:21 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +        await assert.isRejected(browser.takeScreenshot(), 'Error in "takeScreenshot" command');
Так а где сама ошибка летящая от `extract`? Нужно явно выше написать, что при вызове с такими-то координатами кидаем из `extract` например ошибку - `o.0`. И потом просто проверяем, что она дополнена нашей ошибкой.

2023-03-16 12:38 UTC, DudaGod approved these changes
В остальном /ok
Не забудь коммиты правильно сосквошить.

2023-03-16 12:38 UTC, DudaGod commented on lib/commands/screenshot.js
> +            return await sharp(Buffer.from(screenshotResult, 'base64'))
а зачем тут `await`?

2023-03-16 12:38 UTC, DudaGod commented on test/lib/commands/screenshot.js
> +            'sharp': mkSharpInstance
`sharp` можно без кавычек одинарных писать

2023-03-16 12:42 UTC, c1825846 commented on lib/commands/screenshot.js
> +            return await sharp(Buffer.from(screenshotResult, 'base64'))
чтобы в случае возникновения ошибки корректно отработал catch https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise

2023-03-16 21:23 UTC, xrsd commented on lib/commands/screenshot.js
> +                .extract({left: cropCoords.left, top: cropCoords.top, width: cropCoords.width, height: cropCoords.height})
[nit](https://stackoverflow.com/questions/27810522/what-does-nit-mean-in-hacker-speak): _jfyi_

Можно было бы просто написать:

```
.extract(cropCoords)
```

Так как `cropCoords` [является объектом с нужными свойствами](https://github.com/gemini-testing/hermione-safari-commands/blob/master/lib/command-helpers/element-utils/common/index.js#L74).

В тех же случаях, когда нужно стопроцентно гарантировать, что используемая функция не испортит исходный объект, так как он используется дальше, можно было бы клонировать его через:

```
.extract({...cropCoords})
```

В крайнем случае, если нужно подчеркнуть сигнатуру вызываемой функции, или если `cropCoords` может содержать лишние свойства, можно применить для краткости деструктуризацию:

```
const {left, top, width, height} = cropCoords;
...
.extract({left, top, width, height})
```

2023-03-23 15:15 UTC, DudaGod commented
Will be released here - https://github.com/gemini-testing/hermione-safari-commands/pull/25

2023-03-23 15:15 UTC, closed without merging